### ISSUE TITLE
Added standard, but config resets instantly

### ISSUE THREAD

**Issue by paulcanning** [WordPress-Coding-Standards/WordPress-Coding-Standards#1127]
I cloned the WPCS repo and added it to PHPCS via the `--config-set installed_paths` method and afterwards checked using `phpcs -i`, which showed the new WP standards.

However, when I run `phpcs -i` again, the standards are missing.

PEAR and PHPCS are fully up to date.

**Comment by GaryJones** [comment]
That's an odd one.

Just check that you're using the same version of PHPCS, and not some other globally (or project-level) version by accident.

And that you've not got something checking out fresh versions of PHPCS (since the registration of a standard is stored in a file inside the PHPCS codebase).

**Comment by paulcanning** [comment]
so it seems I needed to add the standard whilst in the PHPCS directory (I was trying from my project directory previously) and it is now working. Thanks :)
