### ISSUE TITLE
No way to configure Generic.Formatting.MultipleStatementAlignment to ignore grouping by newlines

### ISSUE THREAD

**Issue by mundschenk-at** [WordPress-Coding-Standards/WordPress-Coding-Standards#1187]
At the moment, there does not seem to be a way to consciously make `Generic.Formatting.MultipleStatementAlignment` allow aligment across "groups". For example, I'd like this constructor (slightly simplified from the real world example) to stay as is alignment-wise:

```php
public function __construct( $version, $basename, Transients $transients = null, Cache $cache = null ) {
	// Basic set-up.
	$this->version           = $version;
	$this->local_plugin_path = $basename;

	// Initialize cache handlers.
	$this->transients        = ( null === $transients ) ? new Transients() : $transients;
	$this->cache             = ( null === $cache ) ? new Cache() : $cache;
}
```

**Comment by JDGrimes** [comment]
You are right, this doesn't appear to be configurable:

https://github.com/squizlabs/PHP_CodeSniffer/blob/c7e73b44fc6f289217e6a5785c7b0fae33889eaa/src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php#L119

As this sniff is part of PHPCS itself and not WPCS, you might want to [open an issue there](https://github.com/squizlabs/PHP_CodeSniffer/issues/) instead. In order to change this in WPCS, we'd have to duplicate that sniff.

**Comment by mundschenk-at** [comment]
I've opened https://github.com/squizlabs/PHP_CodeSniffer/issues/1700 upstream.
