### ISSUE TITLE
XSS: use of wp_kses_post within apply_filters

### ISSUE THREAD

**Issue by superbia** [WordPress-Coding-Standards/WordPress-Coding-Standards#1188]
PHPCS 3.1.0, WPCS 0.13.1, WordPress-VIP

The following code triggers a WordPress.XSS.EscapeOutput.OutputNotEscaped error.
```php
echo apply_filters( 'the_content', wp_kses_post( $content ) );
```
Is this correct? Should I just whitelist this code?

**Comment by JDGrimes** [comment]
Yes, that is correct behavior. We have no way of knowing what filter functions might be applied there, so there is the possibility that they would not escape the filtered data. You could either apply `wp_kses_post()` *after* applying the filters instead, or you could just whitelist this code. Which you choose to do will depend on whether you expect filters on `the_content` adding content that would be broken by `wp_kses_post()`.

**Comment by dingo-d** [comment]
This happens because you are echoing out the `apply_filters`. General workaround would be

~~~php
$new_content = apply_filters( 'the_content', wp_kses_post( $content ) );
echo wp_kses_post( $new_content );
~~~

The problem with this is that `the_content` filter triggers the embedd and shortcode rendering and several other filters. So if you escape it there is a very high chance that your content won't be displayed correctly...

**Comment by superbia** [comment]
Thanks for the quick replies 😃  I can't run wp_kses again on the filtered content without breaking embeds etc. I might refactor the code into a function and whitelist that.
