### ISSUE TITLE
Faulty core fixes: Lines in the same scope not being given the same indent level

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#1191]
Given the following example:

```php
<?php

$foo = 1;

    $bar = 2;

$baz = 4;
```

`$bar` isn't losing its indentation.

Core ref: src/wp-admin/menu.php

Tested with PHPCS `master`, WPCS `develop`.

**Comment by jrfnl** [comment]
The `Core` ruleset currently has the `exact` property for that sniff set to `false`.

```xml
<rule ref="Generic.WhiteSpace.ScopeIndent">
	<properties>
		<property name="exact" value="false"/>
		<property name="indent" value="4"/>
		<property name="tabIndent" value="true"/>
		<property name="ignoreIndentationTokens" type="array" value="T_HEREDOC,T_NOWDOC,T_INLINE_HTML"/>
	</properties>
</rule>
```

Changing that to `true` would fix this, but will have unintended side-effects as it will also affect code like this:

```php
$my_var = 'something'
	. 'else';
```

... which would then be "fixed" like...
```php
$my_var = 'something'
. 'else';
```

I believe that it makes sense to leave the `exact` property as `false`.

As a one-time-only (or maybe once-a-year) action, you could manually verify all these instances after the big fixer run has been done.
To manually verify whether the indent is intentional or accidental, temporarily change the `exact` property to `true` (overrule it via a custom ruleset) and just run the one sniff against the codebase using the `--sniffs=Generic.WhiteSpace.ScopeIndent` command-line addition.

Does that sound reasonable ?

**Comment by pento** [comment]
Yah, that sounds reasonable. Thanks for the insight. 🙂
