### ISSUE TITLE
print_r

### ISSUE THREAD

**Issue by connerbw** [WordPress-Coding-Standards/WordPress-Coding-Standards#1250]
I am very interested in finding leftover `print_r` variables.

However, `print_r()` has two parameters. To capture the output of print_r() I use the return parameter. When this parameter is set to TRUE print_r() will return the information rather than print it. When I do this I am not using it for logging. I'm using it to create a string of output similar to how `wp_json_encode` could be used. 

When I do:

```
<exclude name="WordPress.PHP.DevelopmentFunctions.error_log_print_r"/>
```

I exclude both cases. 

My request is that the print_r rule be split into two separate rules. One for the echo version, another for the encode version. Something like:

```
WordPress.PHP.DevelopmentFunctions.error_log_print_r
WordPress.PHP.DevelopmentFunctions.error_log_print_r_return
```

(Better name welcome)

Thank you for your consideration.

**Comment by JDGrimes** [comment]
Depending on how often you use this in your code, it might be a case where you should just whitelist those particular locations (this will become easier in PHPCS 3.2).

I also wonder why you need to use `print_r()` rather than switching to `wp_json_encode()`.

All things considered, I doubt that this pattern is common enough that your request will be implemented; I suspect that in most cases `print_r()` is being used much the same way regardless of whether or not the second parameter is set to `true`. Of course, you are welcome to customize the sniff, and PRs are welcome. 😃 

I'll leave this open for now at least, in case there is more interest. Maybe this pattern is more common than I think.

**Comment by connerbw** [comment]
Close as won't fix. It's fine. Thanks for asking.

**Comment by jrfnl** [comment]
@connerbw Thanks for getting back to me.
