### ISSUE TITLE
The $text arg must be a single string literal, not "$var"

### ISSUE THREAD

**Issue by killua99** [WordPress-Coding-Standards/WordPress-Coding-Standards#1255]
Hi.

I'm running into an issue where I could not find a way to bypass a error message.

Code example:

```
		<div class="warning-text" style="<?php echo esc_attr( $style_message ); ?>">
			<p><?php esc_html_e( $options['content']['textarea_warning_text'], 'custom-cookie-message' ); ?>
				<a style="<?php echo esc_attr( $style_link ); ?>" href="<?php echo esc_url( $options['general']['cookies_page_link'] ); ?>" title="<?php esc_html_e( $options['content']['input_link_text'], 'custom-cookie-message' ); ?>"><?php esc_html_e( $options['content']['input_link_text'], 'custom-cookie-message' ); ?></a>
			</p>
			<a id="custom-cookie-message-preference" class="button <?php echo esc_attr( $style_button_class ); ?>">
				<?php esc_html_e( $options['content']['input_button_text'], 'custom-cookie-message' ); ?>
			</a>
		</div>
```

The error message is:
```
The $text arg must be a single stirng literal, not "$var"
```

I'm not pointing that the Error message could be wrong, my question is how could I whitelist this error, since this code is in a template for a plugin where that text come from a setting option.

My phpcs version is: `PHP_CodeSniffer version 3.1.1 (stable) `
My WPCS version is: `"wp-coding-standards/wpcs": "^0.13.1"`

You could read the entire code here. https://github.com/killua99/custom-cookie-message/blob/feature/cookie-popup-template/templates/cookie-notice.php

**Comment by GaryJones** [comment]
`esc_html_e()` is for internationalising (and escaping) plain strings in code. Not for strings stored in a database. By the time it's stored, the chance to internationalise it with the usual functions has gone.

There are, I believe, other workarounds that work with WPML, but I'm not overly familiar with them.

So, there's no whitelisting needed here - just change `esc_html_e` to `esc_html` and remove the second arg.

**Comment by killua99** [comment]
Why should I change the function when it clearly is the best use, and data validation in WordPress.

Both function start with the same object, to escape the front-end in the right way, and use the _e in order to add the ability to translate it. If WPCS accept esc_html to pass a variable and not esc_html_e I see it like is not coherent.

Both functions use the same parameter:

esc_html
```
$text
    (string) (required) Text to escape

        Default: None 
```

esc_html_e
```
$text
    (string) (required) Text to translate

        Default: None 
```

I see it right to add or allow variables inside `esc_html_e()` and `esc_html__()`

**Comment by JDGrimes** [comment]
I am not familiar with WPML, but the reason that you normally shouldn't pass a variable to translation functions is because the POT file cannot automatically be generated then (because the string to translate isn't within the function call, so an automatic parser can't find it).

Because of that, there is no whitelisting comment specifically for this sniff, but you can always use `// @codingStandardsIgnoreLine`.  You could also exclude this particular error in your custom ruleset:

```
<exclude name="WordPress.WP.I18n.NonSingularStringLiteralText" />
```

I'm still not sure that you should be passing a variable to this function though...

**Comment by GaryJones** [comment]
> Why should I change the function when it clearly is the best use, and data validation in WordPress.

@killua99 I think you've missed the point of my post.

It's not about the escaping. 

It's about you trying to internationalise a variable. Yes, it might be a variable that, when parsed with a PHP engine, happens to resolve to a string, but that's not how the WP i18n tools work.

See [Law the First](http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/).

`esc_html_e()` is not the best function to use here, because you don't have the plain text string - only a variable holding a string. In an environment where the extraction of strings doesn't execute PHP, then it can't read what your variable holds. Since this is a non-starter, WPCS helpfully points out with a very clear message: `The $text arg must be a single string literal, not "$var"`.

What you really want here is:

```php
<?php echo esc_html( $options['content']['textarea_warning_text'] ); ?>
```

I don't know how the rest of your plugin works, but if someone wants the warning message in a different language, then they would choose the language at the point of input, and not on output.

**Comment by killua99** [comment]
I see the point of you guys, and thanks for the options you show me here. I do understand that in this case, is my fight. Also I do understand and I'm not 100% happy passing a variable into an _e function, coming from Drupal I'm more than clear that is not the best way to work with translation. Just curios if there was a whitelist for that case because I know what I'm doing there.

So I'm going to use the option that @GaryJones mention, and just use `esc_html()` and see how it work.

I'm just going to leave this extra info for documentation purpose, I do believe could be useful for someone out there. But this issue matter add nothing to the conversation and for this could be close, I guess nothing else could be added to it, thanks for clarify all. 😀

When do you work in a multilingual WordPress site you have two good options, WPML or Polylang. The last one (Polylang) as very nice one and nice to work with translations in WordPress and in our experience we like it more than the old friend WPML.

The case is, WPML has an ability to create a map file for customs fields and extra strings to be available for translations. You work with a file called `wpml-config.xml` that files map yours fields and the PO files will be created just right.

With Polylang you could use functions like `pll_e()` that they do the translation coming from they register strings. Also works the normal translations and escapes likek `esc_html_e()` (that's the reason I was using it).

https://wpml.org/documentation/support/language-configuration-files/#admin-texts
https://polylang.pro/doc/the-wpml-config-xml-file/

**Comment by jrfnl** [comment]
@killua99 Just FYI - For multilingual websites, there is a third option: Multilingual Press. From all I've heard, that is nowadays the preferred choice.
Ref: https://wordpress.org/plugins/multilingual-press/
