### ISSUE TITLE
Posts Per Page sniff has long/redundant name

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#1442]
The name `WordPress.WP.PostsPerPage.posts_per_page_posts_per_page` has the words "post per page" _three_ times.

Can it be renamed?

**Comment by jrfnl** [comment]
There's a reason for that.

The errorcode in this case is build up like so:
`Standard.Category.SniffName.functiongroup_functionname`.

The [function group can be excluded](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#excluding-a-group-of-checks).
A function group can contain one or more functions - in the example you mention, the group contains two functions -, which is why the function name called is part of the error code too to just exclude that particular error, not the whole group.

The same principle is used for the error codes in all sniffs using the `exclude` property. Changing the name would not make the name more predictable, nor more logical. It would also create BC-break for anyone who *has* excluded either the function group or the error code, either via a custom ruleset or using inline annotations, making it a change which could only be made in a major release.

Anyway, why does it bother you ? Errorcodes are only really useful for custom ruleset maintainers, not for end users, so end-users normally would never see the code.

**Comment by paulschreiber** [comment]
I expected `WordPress.WP.PostsPerPage.too_high`, which is more descriptive of the problem.

As an end user, I use sniff names often — either in`phpcs.xml` or in `// phpcs:ignore` comments.

**Comment by jrfnl** [comment]
Error codes are not intended to be descriptive - that is what the error messages are for.
Error code are intended to be usable.

To be optimally usable, error codes have to be modular, i.e. exclude one specific issue. This sniff has two different error codes as it has one group with two functions in it, so each error can be individually excluded.
Alternatively, as I stated above, the whole group can be excluded using a property. The first part of the error message makes it easier to figure out the group name to use for the `exclude` without having to look at the PHP code of the sniff itself.

And while it may seem a bit much for this sniff with only one group and two functions, other sniffs which are build on the same principle / same abstract class basis, might have fifteen groups with some groups having up to ten or more functions in it.

Having the errorcode be `toohigh` would take all that usability away from the sniff.

On a practical note:
If you use them in `// phpcs:ignore` comments, you can add a note to these explaining why you are excluding the message, so something like:
```php
// phpcs:ignore WordPress.WP.PostsPerPage.posts_per_page_posts_per_page -- "Too high post limit" is by design in this case.
```

The ignore comments also work on whole sniffs or categories, i.e.:
```php
// phpcs:ignore WordPress.WP.PostsPerPage -- "Too high post limit" is by design in this case.
```
... which would be perfectly fine to use as it is only applicable to that line anyway.

Also note that, if for your project a different post limit would be more reasonable, you can change what is considered "too high" for this sniff. See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#wp-postsperpage-post-limit
