### ISSUE TITLE
Error: phpcs: Referenced sniff "PSR12.Keywords.ShortFormTypeKeywords" does not exist

### ISSUE THREAD

**Issue by prionkor** [WordPress-Coding-Standards/WordPress-Coding-Standards#1622]
## Bug Description

After adding WordPress to phpcs config I see error

phpcs: Referenced sniff "PSR12.Keywords.ShortFormTypeKeywords" does not exist

## Minimal Code Snippet

```php
// Place your code sample here.
```
The error shows up on every keypress.

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | PHP 7.2.10-0ubuntu0.18.04.1 (cli)
| PHP_CodeSniffer version | 3.2.3
| WPCS version            | master branch
| WPCS install type       | e.g. Composer global
| IDE (if relevant)       | VS Code, with plugin phpcs from Ioannis Kappas installed

## Tested Against `develop` branch?
- [x ] I have verified the issue still exists in the `develop` branch of WPCS.
- Tried with master, develop

**Comment by jrfnl** [comment]
Please update your PHPCS install. The latest release of WPCS - 2.0.0-RC1 - has a minimum requirement of PHPCS 3.3.1. The version you are using `3.2.3` is too low.

As it is a composer install, you should be fine if you just run `composer update --with-dependencies wp-coding-standards/wpcs`.

As a side note: using version constraints in your composer file instead of pointing to `dev-master` is the better practice.

**Comment by prionkor** [comment]
After installing latest version of phpcs (v3.4.0) the error was resolved. Thank you for your time!
