### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#350]
I'd like to make a suggestion: could we use GitHub milestones to give a little more structure to the releases?

Right now we're not really using milestones, and I guess releases are kinda just tagged whenever we feel like it (unless I'm missing something). I don't mind being loose about this, but I think it is easier for those watching at home to follow along with the project if they have an idea of when the next release might be, or at least what they can expect to be in it. It might also help us to decide when a bug should be fixed in `master` and not just `develop` (as far as I know this hasn't really happened up to now).

I'm not suggesting we have to have rigid release dates, or scope out each release ahead of time. I've just been thinking it might be good to set the milestone on issues we really want to get into the next release, and have some kind of general goal for when that release might drop. People might like to know about when to expect the next release to they can test it against their projects beforehand (if they aren't already running against `develop` anyway).

Thoughts?

*(Note: this is __not__ meant to be a nudge to tag 0.4.0)*

**Comment by GaryJones** [comment]
+1. Since this project is about ongoing improvements, I'd be happy to see milestones / releases done on a monthly basis i.e. 1st May is the target date for 0.4.0, 1st June is the target date for 0.5.0. That way, we get a known schedule that people can look forward to, and fixes and improvements aren't sitting for months before being usable by anyone using the `master` branch.

Adding a milestone to a ticket then becomes less of "I want to see this in the next release" and more "I think I can code this within this month".

Have a milestone of "Future Release", and any improvements wanted, but not yet scheduled for a release can go under that, which is more confirming of approval for the fix / idea, than having no milestone.

---

We're also not using labels very often. We have a custom set of labels, none that I personally find very useful. Could we at least get "Bug" and "Improvement" in there (ideally under their standard colours as in new repos)?

**Comment by JDGrimes** [comment]
@GaryJones I second everything you said.

> Edit: I've added the default set of labels in under the right colours.

:+1:  That was another thing I was going to mention, but forgot.

**Comment by GaryJones** [comment]
I added a 0.4.0 milestone with a 1st May date, a 0.5.0 with no date and a Future Release milestone with no date. All going to be needed eventually and the tentative date can be changed if others think differently.

I also went back through all of the open tickets, added labels to most of them, closed a few and added a milestone (albeit Future Release) to the one assigned to me.

**Comment by westonruter** [comment]
Great moves!
