### ISSUE TITLE
Suggestions for addition to 'safe' function list / XSS sniff

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#358]
Might these be considered safe ?

`get_the_time()`
`get_the_date()`
`wp_dropdown_pages()`
`paginate_links()`

**Comment by JDGrimes** [comment]
For `get_the_time()` and `get_the_date()`, shouldn't you just be using `the_time()` and `the_date()`? However, these really don't qualify for the auto-escaped functions list, because there is no explicit escaping, and the value is passed through a filter (which means absolutely anything could get incorporated into the value).

`wp_dropdown_pages()` is inconsistent in escaping. It escapes some of the passed arguments but not others. All arguments passed to it should therefore be escaped. Maybe it should be added to the list of printing functions (though direct output can be disabled by setting `echo` to `false`, as you are probably doing).

`paginate_links()` also doesn't escape all of the values passed to it, but it doesn't output the generated HTML directly. This makes things difficult. It might seem like overkill, but I'd suggest you run the function through `wp_kses()`.

**Comment by jrfnl** [comment]
> For get_the_time() and get_the_date(), .... the value is passed through a filter (which means absolutely anything could get incorporated into the value).

Fair point, I retract those.

Regarding wp_dropdown_pages() and paginate_links() - maybe the error message should be made cleared for those kind of functions - saying that variables passed to them should be escaped - would be helpful for people trying to figure out what to do.

**Comment by jrfnl** [comment]
or we could send in a PR to WP Core to make sure the escaping within those last two functions becomes consistent ;-)

**Comment by JDGrimes** [comment]
> or we could send in a PR to WP Core to make sure the escaping within those last two functions becomes consistent ;-)

That would be nice, but it would probably not be accepted, due to concerns with back-compat. See [ticket #17182](https://core.trac.wordpress.org/ticket/17182).

**Comment by JDGrimes** [comment]
I've opened #455 to add `wp_dropdown_pages()` to the printing functions list. This will make escaping errors for it more consistent.

Unless the VIP team speaks to the contrary, I don't think that we should add either `wp_dropdown_pages()` or `paginate_links()` to the list of auto-escaped functions. In case that does happen, #455 can be reverted.

Closing as wontfix for now. Feel free to reopen if the VIP team says that these are OK.

**Comment by johnpbloch** [comment]
For what it's worth, if `paginate_links()` is not allowed in the list of auto-escaped functions, `paginate_comments_links()` should probably also be removed on the same grounds, since it merely passes all arguments blindly to `paginate_links()`.

**Comment by paulcanning** [comment]
Hey folks, I just encountered this issue with `paginate_links()` in my theme. What is the solution to this? Is there a different function I can use?

Thanks!

**Comment by JDGrimes** [comment]
@paulcanning You could either make sure all of the args you pass to it are properly escaped, and then add a whitelisting comment: `// WPCS: XSS OK`. Or, you could pass the result through `wp_kses()`, but you'd probably have to manually construct the list of allowed tags.

**Comment by paulcanning** [comment]
Hmm, i'm not passing any args to it...

**Comment by JDGrimes** [comment]
In that case, you are probably safe to just add the whitelist comment.

**Comment by paulcanning** [comment]
I added the whitelist comment you posted above, but it doesn't seem to clear the warning.

```
<?php
// WPCS: XSS OK.
echo paginate_links();
?>
```

**Comment by JDGrimes** [comment]
The comment goes at the end of the line. This is also covered in the wiki: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors 😃

**Comment by paulcanning** [comment]
I have now!

**Comment by dingo-d** [comment]
I'm looking at [`paginate_links()`](https://developer.wordpress.org/reference/functions/paginate_links/) function, and I'm not 100% sure why this is not in the [$autoEscapedFunctions](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniff.php#L177) variable?

It returns the HTML, but all the `apply_filters` calls are escaped, `aria-current` attribute is escaped. Isn't this safe by design?

**Comment by jrfnl** [comment]
As @JDGrimes says above:

> paginate_links() also doesn't escape all of the values passed to it, but it doesn't output the generated HTML directly. This makes things difficult. It might seem like overkill, but I'd suggest you run the function through wp_kses().

I've just had a look at the function to see if the status has changed, but it hasn't.
While most arguments are escaped within the function, the following are not:
* `$args['prev_text']`
* `$args['before_page_number'] . number_format_i18n( $n ) . $args['after_page_number']`
* `$args['next_text']`

**Comment by dingo-d** [comment]
Oh, ok. Then the `paginate_comments_links` should be removed from the list as it either echoes or returns the `paginate_links` function.

**Comment by jrfnl** [comment]
@dingo-d Yes please ;-)
