### ISSUE TITLE
Documentation for all the whitelist comments

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#446]
It's difficult to determine which whitelist comments (eg. `WPCS: sanitization ok`) are available to use. These should be documented, and it would be good if the documentation recommended a standard format such as `// WPCS: sanitization ok`.

Here's the list I have. Are there more?

 * Escaping: `XSS`
 * Sanitising: `sanitization`
 * Nonce verification: `CSRF`
 * Loose comparison: `loose comparison`
 * Overriding WordPress globals: `override`
 * Use of superglobal: `input var`

**Comment by JDGrimes** [comment]
Previously: #361

**Comment by JDGrimes** [comment]
Related: #228

**Comment by westonruter** [comment]
Note also that I've proposed a way to standardize these whitelisting comments in a model following JSCS, as opposed to our current _ad hoc_ system: https://github.com/squizlabs/PHP_CodeSniffer/issues/604

Example:

```php
echo $do_you_trust_me; // @codingStandardsIgnoreLine WordPress.XSS.EscapeOutput 
```

**Comment by JDGrimes** [comment]
[Uses of `::has_whitelist_comment()`](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/search?utf8=%E2%9C%93&q=has_whitelist_comment).

[Uses of `preg_match()`](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/search?utf8=%E2%9C%93&q=preg_match+ok&type=Code).

There are two more to add to your list from the direct database query sniff:

- Direct database query: `db call`
- Database query without caching: `cache`

The reason that these don't use `::has_whitelist_comment()` is because they check for comments differently than the other sniffs did, so the transition would not have been backward compatible.

**Comment by JDGrimes** [comment]
Note also: there is a [wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki), and you are welcome to contribute to it. :smile:

**Comment by johnbillion** [comment]
Done! https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors

**Comment by JDGrimes** [comment]
Thanks @johnbillion. I've added [a section cautioning against overuse](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors#when-to-use), and explaining how to refactor the example to actually fix it without adding the whitelisting flag.
