### ISSUE TITLE
False positive: Use placeholders and $wpdb->prepare()

### ISSUE THREAD

**Issue by maslade** [WordPress-Coding-Standards/WordPress-Coding-Standards#508]
I have a few lines of code that make use of ```$wpdb->prepare()```, but no matter how I structure it I receive an error.  My code:

    $sql = sprintf( 'SELECT `post_id`, `meta_value` FROM `%s` WHERE `meta_key` = "sort_order" AND `post_id` IN (%s)',
    			$wpdb->postmeta,
    			implode( ',', array_fill( 0, count( $post_ids ), '%d' ) )
    		);
    $sql = $wpdb->prepare( $sql, $post_ids );
    $all_post_meta = $wpdb->get_results( $sql );

The error:  ```Use placeholders and $wpdb->prepare(); found $sql```.

If I condense it all into one line, so the placeholders and ```prepare()``` call are all in the same place, it still produces the same error.

    $all_post_meta = $wpdb->get_results( $wpdb->prepare( sprintf( 'SELECT `post_id`, `meta_value` FROM `%s` WHERE `meta_key` = "sort_order" AND `post_id` IN (%s)',
    		$wpdb->postmeta,
    		implode( ',', array_fill( 0, count( $post_ids ), '%d' ) )
    	),
    	$post_ids )
    );

**Comment by JDGrimes** [comment]
This is similar to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/469. There really isn't much that we can do to avoid some false positives like this. The solution is to whitelist the line of code that the error is appearing on with `// WPCS: unprepared SQL OK.`

**Comment by maslade** [comment]
Roger.  I'll add that to my code.

If you don't mind elaborating - what is it keying off of to conclude that escaping is necessary?  I thought my problem might have been related to #469 initially, which is why I tried squeezing everything into a single statement.  I figured the parser would see this as ```get_results``` being called with a ```prepare``` as its first argument, which would satisfy it.

**Comment by JDGrimes** [comment]
What was keying it off was the `$post_ids` variable in `count( $post_ids )`. Actually, after looking at this closer, I think that maybe this sniff could use some work. It is only looking for variables being incorporated into the query string in some way. But it really should be flagging functions too, like `sprintf()` in your example. That's what I originally thought was probably causing the problem. (Though really `sprintf()` isn't a function that has to be flagged, we just need to check the parameters passed to it, like we do in the XSS sniff.) 

So after looking at this again, I think this is a legitimate bug. The sniff should be flagging when a function call is incorporated into the query string, but it should also be providing special handling for some functions, like the ones you used. Ultimately I think I can eliminate this false positive.

**Comment by DevKishan** [comment]
> This is similar to #469. There really isn't much that we can do to avoid some false positives like this. The solution is to whitelist the line of code that the error is appearing on with `// WPCS: unprepared SQL OK.`

I am having the same issue and can't use variables for table/column names in dynamic queries.

It raises the following issues
 42 | ERROR | Use placeholders and $wpdb->prepare(); found $column_names (WordPress.DB.PreparedSQL.NotPrepared)
 43 | ERROR | Use placeholders and $wpdb->prepare(); found $table_name (WordPress.DB.PreparedSQL.NotPrepared)

![image](https://user-images.githubusercontent.com/21952931/89118959-e3951480-d4c7-11ea-9d9c-58207481c278.png)

Also, adding comments like `// WPCS: unprepared SQL OK.` OR `// phpcs:ignore` aren't doing the trick since 
we need to use  --ignore-annotations  option while running the phpcs command.

I am using PHP_CodeSniffer version 3.5.5 (stable) and WordPress Standard Version 2.3.0 if that helps.

**Comment by GaryJones** [comment]
@DevKishan Since in your particular example, the table name is static (`wp_contacts`), and ignore comments don't seem to be feasible, could you just use the table name directly?

**Comment by DevKishan** [comment]
@GaryJones Thanks for your response. 

I hope if it was possible to use the table name directly in the query, but the code which I added in my comment is just an example code where we are facing the issue but actual code expects dynamic table and column names in the queries.

In order to reduce the code duplication, we are using a helper class for database related queries that returns the data based on the passed arguments like table name, required column names, and where clause conditions. Using table names directly in the query may prevent us from using the helper class.

If there can be a way through which table and column names can be passed dynamically while making sure all placeholder values are escaped properly, I think that would be helpful for us to use the existing helper class without making much changes in the code.

**Comment by jaspindersingh91ie** [comment]
@DevKishan , I hope your issue is resolved. I also get into this issue recently. So I did the following to bypass the phpcs warning:

global $wpdb;
// $cms_id and $user_id were dynamic in my case
$table_name = $wpdb->prefix . $cms_id . '_posts';
$posts_count = $wpdb->get_results(
	$wpdb->prepare( 
	// phpcs:ignore WordPress.DB.PreparedSQLPlaceholders.UnquotedComplexPlaceholder
	'SELECT count(ID) as posts_count FROM %1s WHERE post_author=%d',
	$post_table_name,
	$user_id 
	),
	ARRAY_A);

**Comment by krokodok** [comment]
I just found this issue and just wanted to add, that the whitelist comment `// WPCS: unprepared SQL OK.` from the first answer is now deprecated and should be replaced by `// phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared`.

Find the rule for your issue here: https://github.com/WordPress/WordPress-Coding-Standards/tree/develop/WordPress/Sniffs/DB
