### ISSUE TITLE
sanitize_text_field need to be escaped?

### ISSUE THREAD

**Issue by widoz** [WordPress-Coding-Standards/WordPress-Coding-Standards#618]
I got this warning:

> phpcs: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'sanitize_text_field'

Now, **sanitize_text_field** function strip all tags, so I think the use of **esc_html** isn't necessary.

I know that most common use of this function is to sanitize text from the input user, but the function signature say:

> Sanitizes a string from user input or from the database.

So, for example this code is a correct use of the sanitize_text_field function right?

`
$data->header = get_custom_header();
$data->thumbnail_post = get_post( $data->header->attachment_id );
echo sanitize_text_field( $data->thumbnail_post->post_excerpt )
` 

Could sanitize_text_field considered like the esc_* functions?

**Comment by westonruter** [comment]
No, `sanitize_text_field()` should still be escaped as a general rule. Consider an HTML attribute:

(DO NOT DO THIS)
```
<input value="<?php echo sanitize_text_field( wp_unslash( $_GET['s'] ) ) ?>">
```

This is an XSS vulnerability because someone could maliciously try to supply an `s` query param that looks like: `" oninput="alert( 'DO EVIL' )`. Since double quote marks aren't cleaned by `sanitize_text_field` then it is not safe to use for escaping.
