### ISSUE TITLE
Running phpcbf results in a file with a PHP syntax error

### ISSUE THREAD

**Issue by rodrigoprimo** [WordPress-Coding-Standards/WordPress-Coding-Standards#688]
If I run `phpcbf --standard=WordPress-Core` in a file with the following code:

``` php
<?php

function shortcode_box( $atts, $content = null ) {
    extract( shortcode_atts( array( 'type' => 'normal',
                                       'icon' => '' ), $atts ) );

}
```

The modified file will be (notice the extra comma that was added after the semicolon causing a syntax error):

``` php
<?php

function shortcode_box( $atts, $content = null ) {
    extract( shortcode_atts( array(
        'type' => 'normal',
        'icon' => '',
    ), $atts ) );,

}
```

**Comment by jrfnl** [comment]
I've tried to reproduce the issue and while I did see the issue once, I have not been able to reproduce the issue since, no matter what I tried.

Tested with PHPCS `master` and `2.7.0`, WPCS `develop` and `master` (0.10.0).

@rodrigoprimo Please provide more information on how to consistently reproduce the issue.

**Comment by rodrigoprimo** [comment]
@jrfnl thanks for taking the time to test this. I just tested again and got the same results I got when I created this issue. I'm creating a file called `test.php` with the content that I shared above and then I'm running:

```
$ composer create-project wp-coding-standards/wpcs:dev-master --no-dev
$ vendor/bin/phpcbf --standard=WordPress-Core test.php
```

For me this is happening every time I try. Please let me know what else I can share that can help.

**Comment by GaryJones** [comment]
I can replicate this.

@jrfnl - copy and paste the original code from this ticket, including bad indentation and line-wrapping.

**Comment by jrfnl** [comment]
I've tried again and still can't reproduce it, so leaving this one for someone who can.

All the same, it looks like this is actually an upstream issue in `Squiz_Sniffs_Arrays_ArrayDeclarationSniff` and should be moved there as WPCS uses (a copy of) the PHPCS native sniff for this (and yes, there's a reason for using a copy, but that's unrelated - there have been no relevant changes upstream since the last sync).

**Comment by GaryJones** [comment]
Things have changed a bit with WPCS since this bug was opened. The output is now:

```php
<?php

function shortcode_box( $atts, $content = null ) {
	extract(
		shortcode_atts(
			array(
				'type' => 'normal',
				'icon' => '',
			), $atts
		)
	);

}
```

which `php -l` tells me has no syntax errors.
