### ISSUE TITLE
Add exclusion for @header()?

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress-Coding-Standards/WordPress-Coding-Standards#704]
Core uses `@header()` all of the time. Should WPCS ignore this particular suppression?

**Comment by JDGrimes** [comment]
I guess this is being used to suppress potential "headers already sent" errors? Wouldn't headers already being sent indicate some kind of developer error here? So, in that case, I think that core's general philosophy in that regard at this time is to not avoid PHP errors that are caused by developer mistakes. It just makes issues harder to debug.

So unless there is really a good reason for silencing errors here, I don't see the need for the exclusion. Just tell core to get with the program. 😄

**Comment by GaryJones** [comment]
There are plenty of other things core doesn't do, which it should according to its own [community] standards, and I don't feel the need to start offering exclusions for them.

**Comment by danielbachhuber** [comment]
> I guess this is being used to suppress potential "headers already sent" errors?

Correct.

> Wouldn't headers already being sent indicate some kind of developer error here? So, in that case, I think that core's general philosophy in that regard at this time is to not avoid PHP errors that are caused by developer mistakes. It just makes issues harder to debug.

Potentially, although you may still want the response to succeed if some other plugin in the stack is doing it wrong.

I agree suppressing errors makes debugging more difficult. In the case of sending headers though, I'd much prefer the response to succeed than break on a "Headers already sent" error.
