### ISSUE TITLE
WordPress.XSS.EscapeOutput.OutputNotEscaped false positive

### ISSUE THREAD

**Issue by ScreamingDev** [WordPress-Coding-Standards/WordPress-Coding-Standards#715]
Got `WordPress.XSS.EscapeOutput.OutputNotEscaped` for

```
print balanceTags( $this->render() );
```

Please read https://codex.wordpress.org/Data_Validation and tell me how to write this correct so that WordPress-VIP sniff no longer matches there.

**Comment by JDGrimes** [comment]
The data validation article lists that function under input validation, not output escaping. `balanceTags()` does not actually remove unsafe HTML, so it is not an output escaping function on its own. So WPCS is correct to give you a warning here.

The correct fix will depend upon what kind of HTML you expect `$this->render()` to produce. One option is to use `wp_kses()`. You could also consider refactoring the code of `$this->render()` to output the data directly, if possible, and this may make escaping easier, since it would then be done internally. If neither of those options will work for you, and you are confident that `$this->render()` will output safe data, then you can just whitelist that line like this:

```php
print balanceTags( $this->render() ); // WPCS: XSS OK.
```

**Comment by sourcerer-mike** [comment]
I do the comment there / write another ruleset for that.
In general it feels like a problem for me, because in cases of shortcodes or widgets you like to `::render()` them and sometimes `::dispatch()` them. Think of reusing code for a meta-construct that gathers multiple renderings.
While this is your own code you always trust the rendering. Having those two (separated) is a common thing, so it shouldn't lead to a warning from WPCS in my opinion. It felt like "Hey, we like to push you in a non-modular situation." so I opened this issue and hope that no developer follows that impulse.

**Comment by altrovideo** [comment]
Hi all, I've found some false positive like these:

`Problem synopsis      phpcs: WordPress.XSS.EscapeOutput.UnsafePrintingFunction: Expected next thing to be an escaping function (like esc_html_e() or esc_attr_e()), not '_e' (at line 15)`
about his line of code ` <h1 class="page-title"><?php _e( 'Oops! That page can&rsquo;t be found.', 'theme_name' ); ?></h1> `

suggesting to escape near WP functions that doesn't need to be escaped

**Comment by westonruter** [comment]
@altrovideo actually, the escaped version of `_e()` should actually be used here. It should be using `esc_html_e()` because a translation could contain markup there, maliciously or innocently, that could do something bad. See #678.

**Comment by altrovideo** [comment]
Hi @westonruter , first of all my primary intention is to help a powerful tool like this great one you are working at.
That's right, I've reported the wrong example, here it's what else I've found :

``` WordPress.XSS.EscapeOutput.OutputNotEscaped: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'get_theme_mod' ```

```  phpcs: WordPress.XSS.EscapeOutput.OutputNotEscaped: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'get_the_excerpt' (at line 20) ```

and also this alert :

``` phpcs: WordPress.WP.I18n.MissingSingularPlaceholder: Missing singular placeholder, needed for some languages. See https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals (at line 28)``` 

is about this underscore ( _s  framework) string : 

```
printf( _nx( 'One thought on &ldquo;%2$s&rdquo;', '%1$s thoughts on &ldquo;%2$s&rdquo;', get_comments_number(), 'comments title', 'theme_name' ),
number_format_i18n( get_comments_number() ), '<span>' . get_the_title() . '</span>' ); 
```

Who is right: underscore or sniffer?

I'm using `WordPress_Extra` sniffer validation option

Thank you :smile:

**Comment by grappler** [comment]
@altrovideo There is already a PR open for that https://github.com/Automattic/_s/pull/1012

**Comment by JDGrimes** [comment]
I think all of the issues raised here have been dealt with. Closing.
