### ISSUE TITLE
Improving WordPress.XSS.EscapeOutput.OutputNotEscaped

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#744]
I was looking at how we can improve the `WordPress.XSS.EscapeOutput.OutputNotEscaped` sniff. Here are a few things that I found.

### Functions that already are escaped.
- `Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'get_bloginfo'` Escaping of [`bloginfo`](https://github.com/WordPress/WordPress/blob/4.7-branch/wp-includes/default-filters.php#L99) via a filter. `get_bloginfo( 'name' )` should give an error but `get_bloginfo( 'name', 'display' )` should not.
Related: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/147#issuecomment-31956920 https://github.com/Automattic/_s/pull/555

### Variable is secure
Here are a few examples where it should be possible to work out if the data in the variable is safe.

```php
$categories_list = get_the_category_list( esc_html__( ', ', '_s' ) );
if ( $categories_list && _s_categorized_blog() ) {
	printf( '<span class="cat-links">' . esc_html__( 'Posted in %1$s', '_s' ) . '</span>', $categories_list ); // WPCS: XSS OK.
```

```php
function hamburger() {
	$hamburger = '';
	$hamburger .= 'hamburger';
	echo $hamburger;
}
```

Additionally there should be an error on the line where `get_template_directory_uri()` is used and not when it is being echoed.

```php
function hamburger() {
	$hamburger = '';
	$hamburger .= get_template_directory_uri();
	echo $hamburger;
}
```

### Issues with code snippet in error
These are a few cases where the code in the error is either shortened or too much.

- `WARNING | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$strings'` where it actually was `$strings['update-available']`
- `WARNING | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$theme'` where it was `$theme->get( 'Name' )`
- `WARNING | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '"<a href='$facebook_url' title='Facebook' target='_blank' class='facebook-icon'><span class='icon-social-facebook'></span></a>"'` where the code is:
`$facebook_url = esc_url(get_theme_mod('facebook_url', ''));
echo "<a href='$facebook_url' title='Facebook' target='_blank' class='facebook-icon'><span class='icon-social-facebook'></span></a>";`

**Comment by grappler** [comment]
Looking at a few more results 

### Differentiate between functions and variables.
With the following example we can be 100% sure that it is a correct error because it is a know WordPress function.
`Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'home_url' (WordPress.XSS.EscapeOutput.OutputNotEscaped)`

This would be useful for the Theme Review Team. At the moment we have changed the notice from `Error` to `Warning` because there are too many false positives. There are a few results that we can completely trust and it would help to make those an error.

**Comment by JDGrimes** [comment]
> Functions that already are escaped.

See #219 also.

> Variable is secure

Similar has been suggested before, but I'm not sure that it is entirely in the spirit of late escaping, and I have to wonder where do we draw the line? I believe that handling cases like this will just make the sniff more complex and less efficient, while introducing more possibilities of false positives.

This sniff's job is *not* to detect XSS. It is to detect when `echo` is not being escaped. These aren't false-positives, they are the way that the sniff was designed. If we want to allow these to be handled then we'll either need a different sniff or a flag that enables this more advanced checking.

Your first example is so simple that it is pretty obvious that escaping isn't needed. It is also unnecessarily verbose. It is 100 times simpler to refactor that so that no concatenation is used, than it is to refactor the sniff. :-)

The second example is more complex. So complex that I cannot tell at a glance whether the value needs to be escaped or not. *That is the point of this sniff, and of late escaping: you should always be able to tell without having to see any surrounding code that the output is safe.*

So, I think you are looking for a different sniff, perhaps.

> Issues with code snippet in error

This could be improved, the sniff just errors on the first thing that it encounters that shouldn't be there. It could be modified to look ahead and get the rest of the expression.



> Differentiate between functions and variables.

I'm not sure if this still applies after my explanation of the handling of variables or not. We're not really talking about false positives, just poorly constructed code (from the perspective of ease of escaping detection).

----

Really, I think that there are several different issues being addressed here and it would be better to split each of them off into their own tickets (or at the very least each should be handled in a separate PR, but separate tickets help to keep the discussion less intermingled beforehand.)

**Comment by grappler** [comment]
> I think that there are several different issues being addressed here and it would be better to split each of them off into their own tickets

I have created four new issues.

> See #219 also.

By adding a second parameter you can make the output secure.

> Similar has been suggested before, but I'm not sure that it is entirely in the spirit of late escaping, and I have to wonder where do we draw the line? I believe that handling cases like this will just make the sniff more complex and less efficient, while introducing more possibilities of false positives.

I agree that we should escape late but I would prefer to escape a specific piece of data instead of a whole HTML block before it is echoed.

> This sniff's job is not to detect XSS. It is to detect when echo is not being escaped

If that is so that then the class name and folder structure do not illustrate that.

> Your first example is so simple that it is pretty obvious that escaping isn't needed. It is also unnecessarily verbose. 

I don't think it is possible while keeping the variable in the translation. This is an example from underscores starter theme.

I'll close this ticket now.

**Comment by JDGrimes** [comment]
> I don't think it is possible while keeping the variable in the translation. This is an example from underscores starter theme.

Sorry, I got the examples mixed up, meant the second one, not the first. 😊

**Comment by grappler** [comment]
> Sorry, I got the examples mixed up, meant the second one, not the first.

Ok that makes sense, I suppose it comes down to the code fitting around the sniff or the sniff fitting around the code. For the theme reviews it can be sometimes a bit more difficult to force the code to fit around the sniff.
