### ISSUE TITLE
get_function_call_parameters() support for dynamic varaibles

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#823]
As I was working on a sniff for deprecated parameter values. I noticed that for strings the start position did not include any white spaces but when using other values like functions, constants, arrays, or properties the start position included whitespaces.

This is test code
```php
echo bloginfo( function_name() );
echo bloginfo( CONSTANT );
echo bloginfo( array( 'home') );
echo bloginfo( $this->value );
```

My code to check the output.
```php
$parameters[ $position ]['raw']
$this->tokens[ $parameters[ $position ]['start'] ]['type']
$this->tokens[ $parameters[ $position ]['start'] ]['content']
```

These are the results

Raw output | "function_name()" | "CONSTANT" | "array( 'home' )" | "$this->value"
------------ | ------------- | ------------- | ------------- | -------------
Code type for start position | "T_WHITESPACE" | "T_WHITESPACE" | "T_WHITESPACE" | "T_WHITESPACE"
Content for start position | " " | " " | " " | " "

What I expected 

Raw output | "function_name()" | "CONSTANT" | "array( 'home' )" | "$this->value"
------------ | ------------- | ------------- | ------------- | -------------
Code type for start position | "T_STRING" | "CONSTANT" | "T_ARRAY" | "T_VARIABLE"
Content for start position | "function_name" | "CONSTANT" | "array" | "$this"

**Comment by jrfnl** [comment]
> I noticed that for strings the start position did not include any white spaces

@grappler It's unclear to me what your issue is.

AFAICS the function does exactly what it says: it gives the start and end position of the parameter and the *trimmed* raw content.
Whitespace is not disregarded when determining the start/end position as the output of the function should also be usable to do code style checks on parameters. All token types inside parameters are treated the same, string or no string token type.

**Comment by grappler** [comment]
@jrfnl Sorry, I made a mistake, the white space is included if there is only a string too.

I have created a PR which should fix this for all types of data. I find that the start point should be from the point the parameter starts and not after the bracket opens or after the comma.

**Comment by jrfnl** [comment]
@grappler I do not agree and strongly object to your PR.

If all you need to check is the content of a param, you have the `raw` value already.
If you need to check for specific token types or combinations, you should **always** walk the tokens using the `start` and `end` values. That's what they are for.
Having accurate start and end tokens available makes for more efficient and accurate results using this function than walking everything between brackets in various inconsistent ways across different sniffs.

Your proposed change has the following drawbacks:
* The results of the function can no longer be used for checking whitespace code style.
* Having the whitespace removed will very easily mislead people into writing sniffs which just check the start token instead of properly walking the start to end tokens to check whatever they need to check which will lead to buggy sniffs.

**Comment by jrfnl** [comment]
I'm seriously wondering why you want to change this. The only thing I can think of is for the above mentioned second point which would often be the wrong way to go.

If that however is your underlying issue, I would rather suggest an alternative: adding an extra utility function `is_function_param_one_token()` (or something along those lines) which will return false if there are more than one non-whitespace tokens in the param and will return the token array for the one token which is non-whitespace in the param if the param only has one non-whitespace token.

**Comment by grappler** [comment]
Sorry, I see what you mean. I have adapted my code as it is a lot simpler. Closing as it is not needed anymore.
