### ISSUE TITLE
Why is $wpdb->delete cacheable?

### ISSUE THREAD

**Issue by barryceelen** [WordPress-Coding-Standards/WordPress-Coding-Standards#864]
**Noob question** (and probably not directly related):

The `delete` method is marked as cacheable in [DirectDatabaseQuerySniff.php](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/543bd68ede9558ac4c8c6910ec130535af11e465/WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php#L74).  Why would I want to cache a DELETE query?

**Comment by JDGrimes** [comment]
Not entirely noob, there was some confusion about this back in #180 (from me 😊). The fact is though, that if you added something to the cache at some point, then you will probably want to remove it from the cache when it is deleted, to free up the cache. So that's why `$wpdb->delete()` is still flagged—not to add to the cache, but to delete from it.

**Comment by JDGrimes** [comment]
Maybe there is a way that we can make this more obvious though?

**Comment by barryceelen** [comment]
…which reminds me to check existing issues before opening a new one 🙈.
Thanks @JDGrimes!
